model:
  type: RTDETR
  backbone:
    type: ResNet50
    pretrained: true
    frozen_stages: -1
    output_stride:
    - 8
    - 16
    - 32
    out_channels:
    - 512
    - 1024
    - 2048
  encoder:
    type: HybridEncoder
    in_channels:
    - 512
    - 1024
    - 2048
    hidden_dim: 256
    num_encoder_layers: 1
    expansion: 1.0
    depth_mult: 1.0
    use_encoder_idx:
    - 2
  decoder:
    type: RTDETRTransformer
    hidden_dim: 256
    num_queries: 300
    num_decoder_layers: 6
    num_heads: 8
    dim_feedforward: 1024
    dropout: 0.0
    activation: relu
    num_denoising: 100
    label_noise_ratio: 0.5
    box_noise_scale: 1.0
    learn_query_content: false
  criterion:
    type: RTDETRCriterion
    weight_dict:
      loss_vfl: 1.0
      loss_bbox: 5.0
      loss_giou: 2.0
    losses:
    - vfl
    - boxes
    alpha: 0.75
    gamma: 2.0
    matcher:
      type: HungarianMatcher
      cost_class: 2.0
      cost_bbox: 5.0
      cost_giou: 2.0
input:
  width: 1920
  height: 1080
  channels: 3
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
data:
  dataset_type: COCODataset
  num_classes: 80
  train:
    root: data/coco/train2017
    annotation: data/coco/annotations/instances_train2017.json
    batch_size: 16
    num_workers: 16
    shuffle: true
    drop_last: true
  val:
    root: data/coco/val2017
    annotation: data/coco/annotations/instances_val2017.json
    batch_size: 16
    num_workers: 16
    shuffle: false
    drop_last: false
augmentation:
  train:
  - type: RandomHorizontalFlip
    prob: 0.5
  - type: RandomSelect
    transforms:
    - type: RandomResize
      sizes:
      - - 1920
        - 1080
      keep_ratio: true
    - type: Compose
      transforms:
      - type: RandomResize
        sizes:
        - - 1600
          - 900
        - - 1760
          - 990
        - - 1920
          - 1080
        - - 2080
          - 1170
        - - 2240
          - 1260
        keep_ratio: true
      - type: RandomSizeCrop
        min_size: 960
        max_size: 1920
        respect_aspect_ratio: true
      - type: RandomResize
        sizes:
        - - 1920
          - 1080
        keep_ratio: true
  - type: ColorJitter
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  - type: Normalize
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  val:
  - type: Resize
    size:
    - 1920
    - 1080
    keep_ratio: true
  - type: Normalize
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
training:
  optimizer:
    type: AdamW
    lr: 0.0001
    weight_decay: 0.0001
    betas:
    - 0.9
    - 0.999
  lr_scheduler:
    type: MultiStepLR
    milestones:
    - 40
    - 55
    gamma: 0.1
  epochs: 72
  warmup_epochs: 5
  clip_max_norm: 0.1
  use_amp: true
  accumulate_grad_batches: 1
  pretrained_weights: null
  resume_from: null
  freeze_backbone_epochs: 5
  eval_interval: 2
  save_interval: 5
evaluation:
  metric: coco
  iou_thresholds:
  - 0.5
  - 0.55
  - 0.6
  - 0.65
  - 0.7
  - 0.75
  - 0.8
  - 0.85
  - 0.9
  - 0.95
  max_dets:
  - 1
  - 10
  - 100
  area_ranges:
    all:
    - 0
    - 10000000000
    small:
    - 0
    - 1024
    medium:
    - 1024
    - 9216
    large:
    - 9216
    - 10000000000
  target_metrics:
    AP: 0.525
    AP50: 0.7
    AP75: 0.57
postprocess:
  confidence_threshold: 0.3
  nms_threshold: 0.7
  max_detections: 300
checkpoint:
  save_dir: checkpoints
  save_best: true
  save_last: true
  monitor: AP
  mode: max
logging:
  tensorboard: true
  log_dir: outputs/logs
  log_interval: 50
hardware:
  device: cuda
  gpu_ids:
  - 0
  distributed: false
  num_gpus: 1
  pin_memory: true
  benchmark: true
seed: 42
deterministic: false
debug:
  enabled: false
  overfit_batches: 0
  fast_dev_run: false
